import type { Team } from "./types";

export const teams: Team[] = [
  { name: "Athletics", id: 133 },
  { name: "Pittsburgh Pirates", id: 134 },
  { name: "San Diego Padres", id: 135 },
  { name: "Seattle Mariners", id: 136 },
  { name: "San Francisco Giants", id: 137 },
  { name: "St. Louis Cardinals", id: 138 },
  { name: "Tampa Bay Rays", id: 139 },
  { name: "Texas Rangers", id: 140 },
  { name: "Toronto Blue Jays", id: 141 },
  { name: "Minnesota Twins", id: 142 },
  { name: "Philadelphia Phillies", id: 143 },
  { name: "Atlanta Braves", id: 144 },
  { name: "Chicago White Sox", id: 145 },
  { name: "Miami Marlins", id: 146 },
  { name: "New York Yankees", id: 147 },
  { name: "Milwaukee Brewers", id: 158 },
  { name: "Los Angeles Angels", id: 108 },
  { name: "Arizona Diamondbacks", id: 109 },
  { name: "Baltimore Orioles", id: 110 },
  { name: "Boston Red Sox", id: 111 },
  { name: "Chicago Cubs", id: 112 },
  { name: "Cincinnati Reds", id: 113 },
  { name: "Cleveland Guardians", id: 114 },
  { name: "Colorado Rockies", id: 115 },
  { name: "Detroit Tigers", id: 116 },
  { name: "Houston Astros", id: 117 },
  { name: "Kansas City Royals", id: 118 },
  { name: "Los Angeles Dodgers", id: 119 },
  { name: "Washington Nationals", id: 120 },
  { name: "New York Mets", id: 121 },
];
